### PR TITLE
Feat/amplify appsync simulator

### PR DESCRIPTION
**Pull request by maoosi**
https://github.com/maoosi/prisma-appsync/issues/146

### CODE REVIEW

**Comment by maoosi** [comment]
Hey @cipriancaba - do you have more details or any particular error returned apart from `Cannot GET /`?

I've just tried to entirely delete my `playground` folder and re-create it via `pnpm run dev` and I get access to both the AppSync GraphQL IDE and the GraphQL endpoint at `/graphql`.

Note that I have also updated some of the dependencies and that the new AppSync simulator doesn't support the same `createServer` arguments from before (will create a migration guide for the next release).

@tomschut is everything working correctly on your end - after cloning a fresh `dev` branch and running `pnpm run dev`? Or do you also face the same problem as @cipriancaba ?

**Comment by cipriancaba** [comment]
I am using a slightly modified command to start the server locally. Still using ts-node-dev. 
```
npx ts-node-dev --rs --transpile-only --watch './*.ts' -- ./localServerPublicSchema.ts
```

Here is the output from running that command:
```
🧩 GraphQL server at http://localhost:4002/graphql
🚀 Prisma-AppSync GraphiQL at http://localhost:4002
(node:37358) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.

Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
(Use `node --trace-warnings ...` to show where the warning was created)
```

And this is what I'm passing as args:

```
 createServer({
    schema: schemaPublic,
    lambdaHandler: lambdaHandlerPublic,
    resolvers: resolvers,
    port: 4002,
    // wsPort: 4003,
    watchers: watchersPublic,
    headers: headersPublic,
    yogaServerOptions: {
      cors: true,
      introspection: true,
    },
  })
```

The response for both 

Screenshot 2023-06-18 at 16 52 45

**Comment by maoosi** [comment]
Have you tried running the playground from a fresh install and using the auto-generated boilerplate - just as a test to check whether the issue is specific to your setup, or more global? 

**Few things you can try:**

- The new `createServer` method doesn't have `headers` and `yogaServerOptions` args as it is not using GraphQL Yoga anymore, so you should remove those for now.
- There is a new `resolvers` arg that requires the content from your `resolvers.yaml` file. Make sure it is implemented: https://github.com/maoosi/prisma-appsync/blob/b32143d37325d3c1f9342e0043825b064bbd8766/packages/boilerplate/server/server.ts#L9
- AppSync simulator separates the GraphQL IDE (accessible from `http://localhost:4002`) and the GraphQL Endpoint (accessible via `http://localhost:4002/graphql`). If you try to access `http://localhost:4002/graphql` via your browser it will not work.
- If the above still doesn't work, I would recommend migrating to `vite-node` instead of `ts-node-dev`

**Comment by maoosi** [comment]
@cipriancaba Have you tried running the playground from a fresh install and using the auto-generated boilerplate - just as a test to check whether the issue is specific to your setup, or more global? 

**Few things you can try:**

- The new `createServer` method doesn't have `headers` and `yogaServerOptions` args as it is not using GraphQL Yoga anymore, so you should remove those for now.
- There is a new `resolvers` arg that requires the content from your `resolvers.yaml` file. Make sure it is implemented: https://github.com/maoosi/prisma-appsync/blob/b32143d37325d3c1f9342e0043825b064bbd8766/packages/boilerplate/server/server.ts#L9
- AppSync simulator separates the GraphQL IDE (accessible from `http://localhost:4002`) and the GraphQL Endpoint (accessible via `http://localhost:4002/graphql`). If you try to access `http://localhost:4002/graphql` via your browser it will not work.
- If the above still doesn't work, I would recommend migrating to `vite-node` instead of `ts-node-dev`

**Pull request merged**
