### PR TITLE
Dev server: support fields using arguments with no selectionSet

### PR DESCRIPTION
**Pull request by Tenrys**
also properly name function in `useLambdaEvent.ts` to avoid confusion

### CODE REVIEW

**Comment by maoosi** [comment]
@Tenrys could you please provide an example GraphQL query that demonstrates the problem addressed by this PR?

**Comment by maoosi** [comment]
> also properly name function in `useLambdaEvent.ts` to avoid confusion

Good catch!

**Comment by Tenrys** [comment]
With this schema extension:

```graphql
input UploadDocumentInput {
	name: String!
	kind: DocumentKind!
	completionDate: AWSDateTime!
  validityDate: AWSDateTime!
  customer: DocumentCustomerCreateRelationInput!
  valuation: DocumentValuationCreateRelationInput
  mandate: DocumentMandateCreateRelationInput
  offer: DocumentOfferCreateRelationInput
  promise: DocumentPromiseCreateRelationInput
  deed: DocumentDeedCreateRelationInput
  youSignProcedure: DocumentYouSignProcedureCreateRelationInput
}

extend type Query {
	getDocumentPreSignedUrl(where: DocumentWhereUniqueInput!): AWSURL!	
}
```

And this query:

```graphql
query Query($where: DocumentWhereUniqueInput!) {
  getDocumentPreSignedUrl(where: $where)
}
```

```json
{
  "where": {
    "uuid": "0d4b430c-baa6-43fd-9187-94b93ec70ae2"
  }
}
```

I was getting an error like `Cannot set properties of undefined (setting __args)`. I believe this fixes it, I think it was only an issue on the dev server.

**Comment by Tenrys** [comment]
I added a commit to fix the `isFieldAutopopulated` function counting `false` and `""` and other falsy values as not having a default value, to make it look for `undefined` or `null` instead.

**Comment by maoosi** [comment]
Will be released as part of `1.0.0-rc.6` (you can also try it now with `prisma-appsync@1.0.0-preview.6.7`).

**Pull request merged**
